FROM ghcr.io/mlflow/mlflow:v2.19.0



RUN pip install psycopg2-binary

COPY mlflow_entrypoint.sh /usr/local/bin/entrypoint.sh


RUN chmod +x /usr/local/bin/entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "postgresql://mlflow:mlflow@mlflow-db:5432/mlflow", "--default-artifact-root", "/app/mlruns"]
