from prometheus_client import Counter, Histogram, Gauge

# dans chat
API_REQUEST_TOTAL = Counter(
    "api_request_total",
    "Total number of api requests",
    ["status", "endpoint"]
)

# :::==============================
# dans chat
RAG_REQUEST_TOTAL = Counter(
    "rag_request_total",
    "Total number of RAG requests",
    ["status"]
)

# dans chat
RAG_PROCESSING_TIME = Histogram(
    "rag_processing_seconds",
    "Time spent processing RAG requests",
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0]
)

# dans chat
RAG_METRIC_FAITHFULNESS = Gauge(
    "rag_metric_faithfulness",
    "Faithfulness score from DeepEval",
    ["model"]
)

# dans chat
RAG_METRIC_ANSWER_RELEVANCE = Gauge(
    "rag_metric_answer_relevance",
    "Answer Relevance score from DeepEval",
    ["model"]
)

# dans chat
RAG_METRIC_PRECISION_AT_K = Gauge(
    "rag_metric_precision_at_k",
    "Precision@k score from DeepEval",
    ["model"]
)

# dans chat
RAG_METRIC_RECALL_AT_K = Gauge(
    "rag_metric_recall_at_k",
    "Recall@k score from DeepEval",
    ["model"]
)

# dans chat
RAG_DOCS_RETRIEVED = Histogram(
    "rag_docs_retrieved_count",
    "Number of documents retrieved per query",
    buckets=[1, 3, 5, 10, 20]
)
# :::=================================
# search metrics : 
# :::=================================
SEARCH_REQUEST_TOTAL = Counter(
    "rag_search_requests_total",
    "Total number of search requests"
)

SEARCH_DURATION = Histogram(
    "rag_search_duration_seconds",
    "Total hybrid search duration",
    buckets=[0.01, 0.05, 0.1, 0.3, 0.5, 1, 2, 5]
)

SEMANTIC_DURATION = Histogram(
    "rag_semantic_search_duration_seconds",
    "Semantic search duration"
)

KEYWORD_DURATION = Histogram(
    "rag_keyword_search_duration_seconds",
    "Keyword search duration"
)

SEARCH_DOCS_SEMANTIC = Histogram(
    "rag_semantic_docs_count",
    "Number of semantic retrieved docs",
    buckets=[1,3,5,10,20]
)

SEARCH_DOCS_KEYWORD = Histogram(
    "rag_keyword_docs_count",
    "Number of keyword retrieved docs",
    buckets=[1,3,5,10,20]
)

SEARCH_DOCS_FINAL = Histogram(
    "rag_final_docs_count",
    "Number of final docs returned",
    buckets=[1,3,5,10,20]
)

# search
RAG_HYBRID_SCORE = Histogram(
    "rag_hybrid_result_score",
    "Distribution of hybrid search result scores",
    buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
)


RAG_RETRIEVAL_SIMILARITY = Histogram(
    "rag_retrieval_similarity",
    "Similarity score distribution of retrieved docs",
    buckets=[0.3, 0.5, 0.7, 0.8, 0.9, 1.0]
)

# :::==============================

# RAG_LLM_LATENCY = Histogram(
#     "rag_llm_latency_seconds",
#     "Time spent generating response from LLM",
#     buckets=[0.5, 1, 2, 3, 5, 10, 20]
# )

# RAG_OUTPUT_TOKENS = Histogram(
#     "rag_output_tokens",
#     "Number of tokens generated by LLM",
#     buckets=[50, 100, 200, 400, 800, 1500]
# )

# RAG_INPUT_TOKENS = Histogram(
#     "rag_input_tokens",
#     "Number of tokens sent to LLM",
#     buckets=[200, 500, 1000, 2000, 4000, 8000]
# )